name: FeelBreatheMove
favicon: null
layout_spectrum: 0.29169778688810766
typography_spectrum: 0.62125
title: Feel Breathe Move
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
